export const TERMINAL_NAME = 'terminal';
export const TERMINAL_TYPE = 'myterm';
export const TERMINAL_VERSION = '0.3.0';
export const TERMINAL_COLOR_MODE = 'truecolor';

export const TERMINAL_WELCOME_MESSAGE_LINES = [
    `Command Line Interface v${TERMINAL_VERSION}`, 
    'Type "help" for available commands',
    '',
];

export const TERMINAL_DEFAULT_THEME_NAME = 'pastel-dark';
export const TERMINAL_DEFAULT_FONT_SIZE = 16;
export const TERMINAL_DEFAULT_PADDING = 10;
export const TERMINAL_DEFAULT_SCROLL_BAR_SIZE = 16;

export const TERMINAL_DEFAULT_COLORS = Object.freeze({
    PRIMARY: '#eee',
    SECONDARY: '#ccc',
    ACCENT: '#666',
});

export const TERMINAL_ARROW_SCROLL_LINES_AMOUNT = 1;
export const TERMINAL_WHEEL_SCROLL_LINES_AMOUNT = 4;

export const TERMINAL_CLICK_DETECTION_TIME_THRESHOLD = 200;
export const TERMINAL_CLICK_DETECTION_MOVE_THRESHOLD = 5;

const TERMINAL_CONFIG_STORE_KEY_PREFIX = 'terminal';
export const TERMINAL_CONFIG_THEME_KEY = `${TERMINAL_CONFIG_STORE_KEY_PREFIX}:theme`;
export const TERMINAL_CONFIG_PROMPT_KEY = `${TERMINAL_CONFIG_STORE_KEY_PREFIX}:prompt`;
export const TERMINAL_CONFIG_CURSOR_KEY = `${TERMINAL_CONFIG_STORE_KEY_PREFIX}:cursor`;
export const TERMINAL_CONFIG_SYNTAX_KEY = `${TERMINAL_CONFIG_STORE_KEY_PREFIX}:syntax`;
export const TERMINAL_CONFIG_FONT_SIZE_KEY = `${TERMINAL_CONFIG_STORE_KEY_PREFIX}:font-size`;
export const TERMINAL_CONFIG_PADDING_KEY = `${TERMINAL_CONFIG_STORE_KEY_PREFIX}:padding`;
export const TERMINAL_CONFIG_SCROLL_BAR_SIZE_KEY = `${TERMINAL_CONFIG_STORE_KEY_PREFIX}:scroll-bar-size`;

export default {
    TERMINAL_NAME,
    TERMINAL_TYPE,
    TERMINAL_VERSION,
    TERMINAL_COLOR_MODE,
    TERMINAL_WELCOME_MESSAGE_LINES,
    TERMINAL_DEFAULT_THEME_NAME,
    TERMINAL_DEFAULT_FONT_SIZE,
    TERMINAL_DEFAULT_PADDING,
    TERMINAL_DEFAULT_SCROLL_BAR_SIZE,
    TERMINAL_DEFAULT_COLORS,
    TERMINAL_ARROW_SCROLL_LINES_AMOUNT,
    TERMINAL_WHEEL_SCROLL_LINES_AMOUNT,
    TERMINAL_CLICK_DETECTION_TIME_THRESHOLD,
    TERMINAL_CLICK_DETECTION_MOVE_THRESHOLD,
    TERMINAL_CONFIG_THEME_KEY,
    TERMINAL_CONFIG_PROMPT_KEY,
    TERMINAL_CONFIG_CURSOR_KEY,
    TERMINAL_CONFIG_SYNTAX_KEY,
    TERMINAL_CONFIG_FONT_SIZE_KEY,
    TERMINAL_CONFIG_PADDING_KEY,
    TERMINAL_CONFIG_SCROLL_BAR_SIZE_KEY,
}