export const CALC_SUITE = {
    name: 'calc',
    description: 'Calculator expression evaluation',
    tests: [
        { input: 'calc 2 + 3', expected: '5' },
        { input: 'calc 10 - 4', expected: '6' },
        { input: 'calc 3 * 7', expected: '21' },
        { input: 'calc 20 / 4', expected: '5' },
        { input: 'calc 2 ^ 10', expected: '1024' },
        { input: 'calc 2 + 3 * 4', expected: '14' },
        { input: 'calc (2 + 3) * 4', expected: '20' },
        { input: 'calc 10 / (5 - 3)', expected: '5' },
        { input: 'calc -5 + 3', expected: '-2' },
        { input: 'calc -(2 + 3)', expected: '-5' },
        { input: 'calc 2 ^ 2 ^ 3', expected: '256' },
        { input: 'calc sqrt(144)', expected: '12' },
        { input: 'calc sqrt(2 + 2) * 3', expected: '6' },
        { input: 'calc sin(0)', expected: '0' },
        { input: 'calc cos(0)', expected: '1' },
        { input: 'calc tan(0)', expected: '0' },
        { input: 'calc abs(-42)', expected: '42' },
        { input: 'calc ceil(4.2)', expected: '5' },
        { input: 'calc floor(4.8)', expected: '4' },
        { input: 'calc round(4.5)', expected: '5' },
        { input: 'calc ln(1)', expected: '0' },
        { input: 'calc log2(8)', expected: '3' },
        { input: 'calc log10(1000)', expected: '3' },
        { input: 'calc log(100, 10)', expected: '2' },
        { input: 'calc min(3, 1, 4, 1, 5)', expected: '1' },
        { input: 'calc max(3, 1, 4, 1, 5)', expected: '5' },
        { input: 'calc pow(2, 8)', expected: '256' },
        { input: 'calc pi', expected: `${Math.PI}` },
        { input: 'calc e', expected: `${Math.E}` },
        { input: 'calc sin(pi / 2)', expected: `${Math.sin(Math.PI / 2)}` },
        { input: 'calc 2 * pi * 5', expected: `${2 * Math.PI * 5}` },
        { input: 'calc sqrt(3^2 + 4^2)', expected: '5' },
        { input: 'calc (1+2)*(3+4)/(5-2)', expected: `${(1 + 2) * (3 + 4) / (5 - 2)}` },
        { input: 'calc 1 / 0', expected: 'Error: Division by zero' },
        { input: 'calc 0.1 + 0.2', expected: `${0.1 + 0.2}` },
    ]
}

export default CALC_SUITE
