import { UIBorder, UIColor, UIEdgeSet, UIOffset, UIPoint, UIRect, UIShadow, UIImage } from '../../ui-tool-kit/index.js'
import { IconSet } from './icon-set.js'
import { ImageSet } from './image-set.js'
import { SvgSet } from './svg-set.js'

//MISC
export const DOUBLE_CLICK_DELAY_MILLISECONDS = 500;//if difference between clicks is withing this value then its double click
export const START_MOVING_UI_COMPONENTS_THRESHOLD = 5;//when moving ui components start move only after difference between coordinates greater then this value

//COLORS PALETTE
const PRIMARY_COLOR = new UIColor(0, 0, 0);
const PRIMARY_LIGHT_COLOR = new UIColor(0.15, 0.15, 0.15);
const TEXT_PRIMARY_COLOR = new UIColor(1, 1, 1);
const ICON_PRIMARY_COLOR = new UIColor(1, 1, 1);
const SECONDARY_COLOR = new UIColor(0.48, 0.53, 0.63);

//DEFAULT STYLES
const DEFAULT_SHADOW_COLOR = new UIColor(0, 0, 0, 0.2);
const DEFAULT_SHADOW_BLUR = 15;
const DEFAULT_SHADOW_SPREAD = 5;
const DEFAULT_SHADOW = new UIShadow(DEFAULT_SHADOW_COLOR, UIPoint.zero, DEFAULT_SHADOW_BLUR, DEFAULT_SHADOW_SPREAD);

//LOADING SCREEN
export const LOADING_SCREEN_BACKGROUND_COLOR = UIColor.black;
export const LOADING_SCREEN_TEXT_COLOR = UIColor.white;

export const LOADING_SCREEN_ICON_COLOR = new UIColor(0, 0.8, 1);
export const LOADING_SCREEN_ICON_WIDTH = 100;
export const LOADING_SCREEN_ICON_HEIGHT = 100;

export const LOADING_SCREEN_TEXT_WIDTH = 200;
export const LOADING_SCREEN_TEXT_HEIGHT = 40;

export const LOADING_SCREEN_CONTENT_MARGIN = 20;
export const LOADING_SCREEN_CONTENT_WIDTH = LOADING_SCREEN_TEXT_WIDTH;
export const LOADING_SCREEN_CONTENT_HEIGHT = LOADING_SCREEN_ICON_HEIGHT + LOADING_SCREEN_TEXT_HEIGHT + LOADING_SCREEN_CONTENT_MARGIN;

//DESKTOP
export const DESKTOP_DEFAULT_BACKGROUND_IMAGE = ImageSet.desktopBackground;
export const DESKTOP_MIN_WIDTH = 800;
export const DESKTOP_WINDOW_PLACEHOLDER_BACKGROUND_COLOR = new UIColor(1, 1, 1, 0.05);
export const DESKTOP_WINDOW_PLACEHOLDER_BORDER = new UIBorder(1, new UIColor(1, 1, 1, 0.1));
export const DESKTOP_WINDOW_PLACEHOLDER_PADDING = 10;
export const AUTO_MAXIMIZE_WINDOW_X_THRESHOLD = 2;

//TASK BAR
export const TASK_BAR_HEIGHT = 40;
export const TASK_BAR_BACKGROUND_COLOR = PRIMARY_COLOR;
export const TASK_BAR_HOVER_BACKGROUND_COLOR = new UIColor(0.5, 0.5, 0.5, 0.3);
export const TASK_BAR_TEXT_COLOR = TEXT_PRIMARY_COLOR;
export const TASK_BAR_ICON_COLOR = ICON_PRIMARY_COLOR;

//TASK BAR START
export const TASK_BAR_START_ICON_WIDTH = 48;
export const TASK_BAR_START_ICON_PADDING = 10;
export const TASK_BAR_START_ICON_SVG = SvgSet.window;
export const TASK_BAR_START_HOVER_ICON_COLOR = SECONDARY_COLOR;
//TASK BAR SEARCH
export const TASK_BAR_SEARCH_BAR_BORDER_WIDTH = 1;
export const TASK_BAR_SEARCH_BAR_HOVER_BORDER_WIDTH = 2;
export const TASK_BAR_SEARCH_BAR_BACKGROUND_COLOR = new UIColor(0.93, 0.93, 0.93);
export const TASK_BAR_SEARCH_BAR_HOVER_BACKGROUND_COLOR = new UIColor(1, 1, 1);
export const TASK_BAR_SEARCH_BAR_BORDER_COLOR = new UIColor(0.7, 0.7, 0.7);
export const TASK_BAR_SEARCH_BAR_HOVER_BORDER_COLOR = SECONDARY_COLOR;
export const TASK_BAR_SEARCH_BAR_HEIGHT = TASK_BAR_HEIGHT;

export const TASK_BAR_SEARCH_BAR_ICON_WIDTH = TASK_BAR_SEARCH_BAR_HEIGHT;
export const TASK_BAR_SEARCH_BAR_ICON_HEIGHT = TASK_BAR_SEARCH_BAR_HEIGHT;
export const TASK_BAR_SEARCH_BAR_ICON_SVG = SvgSet.magnifyingGlass;
export const TASK_BAR_SEARCH_BAR_ICON_COLOR = UIColor.black;
export const TASK_BAR_SEARCH_BAR_ICON_PADDING = 12;

export const TASK_BAR_SEARCH_BAR_TEXT_FIELD_WIDTH = 248;
export const TASK_BAR_SEARCH_BAR_TEXT_FIELD_HEIGHT = TASK_BAR_SEARCH_BAR_HEIGHT;
export const TASK_BAR_SEARCH_BAR_TEXT_FIELD_PADDING = new UIOffset(8, UIEdgeSet.right);

export const TASK_BAR_SEARCH_BAR_CONTAINER_WIDTH = TASK_BAR_SEARCH_BAR_TEXT_FIELD_WIDTH + TASK_BAR_SEARCH_BAR_ICON_WIDTH;
export const TASK_BAR_SEARCH_BAR_CONTAINER_HEIGHT = TASK_BAR_HEIGHT;
export const TASK_BAR_SEARCH_BAR_PLACEHOLDER_TEXT_COLOR = UIColor.black;
//TASK BAR TASK
export const TASK_BAR_TASK_DEFAULT_TEXT = 'New Task';
export const TASK_BAR_TASK_DEFAULT_IMAGE = new UIImage('');

export const TASK_BAR_TASK_WIDTH = 150;
export const TASK_BAR_TASK_HEIGHT = TASK_BAR_HEIGHT;

export const TASK_BAR_TASK_ICON_WIDTH = 38;
export const TASK_BAR_TASK_ICON_HEIGHT = 38;
export const TASK_BAR_TASK_ICON_PADDING = 8;

export const TASK_BAR_TASK_LABEL_RIGHT_PADDING = 4;
export const TASK_BAR_TASK_LABEL_WIDTH = TASK_BAR_TASK_WIDTH - TASK_BAR_TASK_ICON_WIDTH - TASK_BAR_TASK_LABEL_RIGHT_PADDING;
export const TASK_BAR_TASK_LABEL_HEIGHT = TASK_BAR_HEIGHT;

export const TASK_BAR_TASK_BOTTOM_BORDER_COLOR = SECONDARY_COLOR;
export const TASK_BAR_TASK_BOTTOM_BORDER_FRAME = new UIRect(4, 0, 142, 2);
export const TASK_BAR_TASK_SELECTED_BOTTOM_BORDER_FRAME = new UIRect(0, 0, 150, 2);

export const TASK_BAR_TASK_BACKGROUND_COLOR = null;
export const TASK_BAR_TASK_SELECTED_BACKGROUND_COLOR = new UIColor(0.48, 0.53, 0.63, 0.5);

//TASK BAR ALL WINDOW BUTTON
export const TASK_BAR_ALL_WINDOW_BUTTON_WIDTH = 5;
export const TASK_BAR_ALL_WINDOW_BUTTON_HEIGHT = TASK_BAR_HEIGHT;
export const TASK_BAR_ALL_WINDOW_BUTTON_BORDER_COLOR = new UIColor(0.5, 0.5, 0.5);
//TASK BAR NOTIFICATION
export const TASK_BAR_NOTIFICATION_CONTAINER_RIGHT = TASK_BAR_ALL_WINDOW_BUTTON_WIDTH;
export const TASK_BAR_NOTIFICATION_CONTAINER_WIDTH = 48;
export const TASK_BAR_NOTIFICATION_CONTAINER_HEIGHT = TASK_BAR_HEIGHT;

export const TASK_BAR_NOTIFICATION_ICON = SvgSet.message;
export const TASK_BAR_NOTIFICATION_ICON_WIDTH = 40;
export const TASK_BAR_NOTIFICATION_ICON_HEIGHT = TASK_BAR_HEIGHT;
//TASK BAR TIME
export const TASK_BAR_TIME_CONTAINER_RIGHT = TASK_BAR_NOTIFICATION_CONTAINER_RIGHT + TASK_BAR_NOTIFICATION_CONTAINER_WIDTH;
export const TASK_BAR_TIME_CONTAINER_WIDTH = 66;
export const TASK_BAR_TIME_CONTAINER_HEIGHT = TASK_BAR_HEIGHT;
//TASK BAR KEYBOARD LANGUAGE
export const TASK_BAR_KEYBOARD_LANGUAGE_CONTAINER_RIGHT = TASK_BAR_TIME_CONTAINER_RIGHT + TASK_BAR_TIME_CONTAINER_WIDTH;
export const TASK_BAR_KEYBOARD_LANGUAGE_CONTAINER_WIDTH = 36;
export const TASK_BAR_KEYBOARD_LANGUAGE_CONTAINER_HEIGHT = TASK_BAR_HEIGHT;
//TASK BAR STATUS ICONS
export const TASK_BAR_STATUS_ICON_WIDTH = 22;
export const TASK_BAR_STATUS_ICON_HEIGHT = TASK_BAR_HEIGHT;
//TASK BAR AUDIO VOLUME
export const TASK_BAR_AUDIO_VOLUME_CONTAINER_RIGHT = TASK_BAR_KEYBOARD_LANGUAGE_CONTAINER_RIGHT + TASK_BAR_KEYBOARD_LANGUAGE_CONTAINER_WIDTH;
export const TASK_BAR_AUDIO_VOLUME_CONTAINER_WIDTH = TASK_BAR_STATUS_ICON_WIDTH;
export const TASK_BAR_AUDIO_VOLUME_CONTAINER_HEIGHT = TASK_BAR_STATUS_ICON_HEIGHT;

export const TASK_BAR_AUDIO_VOLUME_ICON_WIDTH = TASK_BAR_STATUS_ICON_WIDTH;
export const TASK_BAR_AUDIO_VOLUME_ICON_HEIGHT = TASK_BAR_STATUS_ICON_HEIGHT;
//TASK BAR NETWORK
export const TASK_BAR_NETWORK_CONTAINER_RIGHT = TASK_BAR_AUDIO_VOLUME_CONTAINER_RIGHT + TASK_BAR_AUDIO_VOLUME_CONTAINER_WIDTH;
export const TASK_BAR_NETWORK_CONTAINER_WIDTH = TASK_BAR_STATUS_ICON_WIDTH;
export const TASK_BAR_NETWORK_CONTAINER_HEIGHT = TASK_BAR_STATUS_ICON_HEIGHT;

export const TASK_BAR_NETWORK_ICON_WIDTH = TASK_BAR_STATUS_ICON_WIDTH;
export const TASK_BAR_NETWORK_ICON_HEIGHT = TASK_BAR_STATUS_ICON_HEIGHT;
export const TASK_BAR_NETWORK_ICONS = Object.freeze({
    off: SvgSet.globe,
    on: SvgSet.display
});
export const TASK_BAR_NETWORK_DEFAULT_ICON = TASK_BAR_NETWORK_ICONS.off;
//TASK BAR STATUS
export const TASK_BAR_STATUS_WIDTH = TASK_BAR_ALL_WINDOW_BUTTON_WIDTH 
    + TASK_BAR_NOTIFICATION_CONTAINER_WIDTH 
    + TASK_BAR_TIME_CONTAINER_WIDTH 
    + TASK_BAR_KEYBOARD_LANGUAGE_CONTAINER_WIDTH
    + TASK_BAR_AUDIO_VOLUME_CONTAINER_WIDTH
    + TASK_BAR_NETWORK_CONTAINER_WIDTH;

//SHORTCUT
export const SHORTCUT_DEFAULT_NAME = 'New Shortcut';
export const SHORTCUT_DEFAULT_IMAGE = IconSet.file;
export const SHORTCUT_ARROW_IMAGE = IconSet.shortcutArrow;
export const SHORTCUT_BORDER_COLOR = UIColor.transparent;
export const SHORTCUT_BORDER = new UIBorder(1, SHORTCUT_BORDER_COLOR);
export const SHORTCUT_BACKGROUND_COLOR = null;
export const SHORTCUT_SELECTED_BACKGROUND_COLOR = new UIColor(0.65, 0.78, 0.99, 0.4);
export const SHORTCUT_SELECTED_BORDER_COLOR = new UIColor(0.65, 0.78, 0.99);
export const SHORTCUT_SELECTED_BORDER = new UIBorder(1, SHORTCUT_SELECTED_BORDER_COLOR);

export const SHORTCUT_ICON_WIDTH = 70;
export const SHORTCUT_ICON_HEIGHT = 70;
export const SHORTCUT_ICON_PADDING = new UIOffset(5);

export const SHORTCUT_ARROW_WIDTH = 15;
export const SHORTCUT_ARROW_HEIGHT = 15;
export const SHORTCUT_ARROW_X = 2;
export const SHORTCUT_ARROW_Y = SHORTCUT_ICON_HEIGHT - SHORTCUT_ARROW_HEIGHT;

export const SHORTCUT_LABEL_TEXT_COLOR = TEXT_PRIMARY_COLOR;
export const SHORTCUT_LABEL_LINEHEIGHT = 16;
export const SHORTCUT_LABEL_LINES = 2;
export const SHORTCUT_LABEL_WIDTH = SHORTCUT_ICON_WIDTH;
export const SHORTCUT_LABEL_HEIGHT = SHORTCUT_LABEL_LINEHEIGHT * SHORTCUT_LABEL_LINES;
export const SHORTCUT_LABEL_MAX_SYMBOLS = 20;
export const SHORTCUT_LABEL_TEXT_SHADOW = new UIShadow(UIColor.black, new UIPoint(1, 1), 4);

export const SHORTCUT_NAME_EDIT_PADDING_WIDTH = 2;
export const SHORTCUT_NAME_EDIT_X = -SHORTCUT_NAME_EDIT_PADDING_WIDTH;
export const SHORTCUT_NAME_EDIT_Y = SHORTCUT_ICON_HEIGHT - SHORTCUT_NAME_EDIT_PADDING_WIDTH;
export const SHORTCUT_NAME_EDIT_WIDTH = SHORTCUT_LABEL_WIDTH + 2 * SHORTCUT_NAME_EDIT_PADDING_WIDTH;
export const SHORTCUT_NAME_EDIT_HEIGHT = SHORTCUT_LABEL_LINEHEIGHT + 2 * SHORTCUT_NAME_EDIT_PADDING_WIDTH;
export const SHORTCUT_NAME_EDIT_PADDING = new UIOffset(SHORTCUT_NAME_EDIT_PADDING_WIDTH);
export const SHORTCUT_NAME_EDIT_BORDER = new UIBorder(1, UIColor.black);
export const SHORTCUT_NAME_EDIT_BACKGROUND_COLOR = UIColor.white;

export const SHORTCUT_WIDTH = SHORTCUT_ICON_WIDTH;
export const SHORTCUT_HEIGHT = SHORTCUT_ICON_HEIGHT + SHORTCUT_LABEL_HEIGHT;

export const SHORTCUT_GAP = 20;
export const SHORTCUT_INITIAL_COORD = SHORTCUT_GAP / 4;

//WINDOW
export const WINDOW_RESIZABLE_MIN_WIDTH = 200;
export const WINDOW_RESIZABLE_MIN_HEIGHT = 200;
export const WINDOW_RESIZABLE_AREA_WIDTH = 8;

export const WINDOW_BORDER_WIDTH = 1;
export const WINDOW_BORDER_COLOR = UIColor.black;
export const WINDOW_BORDER = new UIBorder(WINDOW_BORDER_WIDTH, WINDOW_BORDER_COLOR);

export const WINDOW_BACKGROUND_COLOR = UIColor.white;
export const WINDOW_ACTIVE_BORDER_COLOR = WINDOW_BACKGROUND_COLOR;

export const WINDOW_TEXT_COLOR = UIColor.black;

export const WINDOW_SHADOW = DEFAULT_SHADOW;

export const WINDOW_ACTION_ICON_SIZE = 32;
export const WINDOW_ACTION_ICON_PADDING = 8;
export const WINDOW_ACTION_ICON_HOVER_COLOR = new UIColor(.9, .9, .9);
export const WINDOW_ACTION_ICON_CLOSE_BG_HOVER_COLOR = new UIColor(.9, .15, .15);
export const WINDOW_ACTION_ICON_CLOSE_HOVER_COLOR = UIColor.white;

export const WINDOW_HEADER_HEIGHT = 32;
export const WINDOW_HEADER_PADDING = 10;

export const WINDOW_ACTION_ICON_MINIMIZE_SVG = SvgSet.windowMinimize;
export const WINDOW_ACTION_ICON_MAXIMIZE_SVG = SvgSet.windowMaximize;
export const WINDOW_ACTION_ICON_RESTORE_SVG = SvgSet.windowRestore;
export const WINDOW_ACTION_ICON_CLOSE_SVG = SvgSet.xMark;

//WIDGET
export const WIDGET_BACKGROUND_COLOR = PRIMARY_LIGHT_COLOR;
export const WIDGET_TEXT_COLOR = TEXT_PRIMARY_COLOR;
export const WIDGET_BORDER_COLOR = new UIColor(0.6, 0.6, 0.6, 0.5);
export const WIDGET_BORDER_WIDTH = 1;
export const WIDGET_BORDER = new UIBorder(WIDGET_BORDER_WIDTH, WIDGET_BORDER_COLOR);
export const WIDGET_SHADOW = DEFAULT_SHADOW;
export const WIDGET_DEFAULT_FRAME = new UIRect(0, 0, 100, 100);
export const WIDGET_ZINDEX = 999999;

//AUDIO WIDGET
export const AUDIO_VOLUME_ICONS = Object.freeze({
    mute: SvgSet.volumeXMark,
    off: SvgSet.volumeOff,
    low: SvgSet.volumeLow,
    normal: SvgSet.volume,
    high: SvgSet.volumeHigh
});
export const AUDIO_VOLUME_DEFAULT_ICON = AUDIO_VOLUME_ICONS.normal;

export const WIDGET_AUDIO_VOLUME_WIDTH = 360;

export const WIDGET_AUDIO_VOLUME_OUTPUT_LABEL_HEIGHT = 40;
export const WIDGET_AUDIO_VOLUME_OUTPUT_LABEL_WIDTH = WIDGET_AUDIO_VOLUME_WIDTH;
export const WIDGET_AUDIO_VOLUME_OUTPUT_LABEL_PADDING = 10;

export const WIDGET_AUDIO_VOLUME_ICON_WIDTH = 60;
export const WIDGET_AUDIO_VOLUME_ICON_HEIGHT = 60;

export const WIDGET_AUDIO_VOLUME_VALUE_LABEL_WIDTH = 60;
export const WIDGET_AUDIO_VOLUME_VALUE_LABEL_HEIGHT = 60;

export const WIDGET_AUDIO_VOLUME_SLIDER_WIDTH = WIDGET_AUDIO_VOLUME_WIDTH - WIDGET_AUDIO_VOLUME_ICON_WIDTH - WIDGET_AUDIO_VOLUME_VALUE_LABEL_WIDTH;
export const WIDGET_AUDIO_VOLUME_SLIDER_HEIGHT = 60;
export const WIDGET_AUDIO_VOLUME_SLIDER_PADDING = new UIOffset(29, UIEdgeSet.vertical);
export const WIDGET_AUDIO_VOLUME_SLIDER_THUMB_FRAME_WIDTH = 8;
export const WIDGET_AUDIO_VOLUME_SLIDER_THUMB_FRAME_HEIGHT = 24;
export const WIDGET_AUDIO_VOLUME_SLIDER_THUMB_FRAME_BORDER_RADIUS = WIDGET_AUDIO_VOLUME_SLIDER_THUMB_FRAME_WIDTH / 2;
export const WIDGET_AUDIO_VOLUME_SLIDER_THUMB_BACKGROUND_COLOR = new UIColor(0.40, 0.45, 0.55);
export const WIDGET_AUDIO_VOLUME_SLIDER_TRACK_BACKGROUND_COLOR = new UIColor(0.5, 0.5, 0.5);
export const WIDGET_AUDIO_VOLUME_SLIDER_TRACK_FILL_BACKGROUND_COLOR = new UIColor(0.5, 0.55, 0.65);

export const WIDGET_AUDIO_VOLUME_HEIGHT = WIDGET_AUDIO_VOLUME_OUTPUT_LABEL_HEIGHT + WIDGET_AUDIO_VOLUME_SLIDER_HEIGHT;

//KEYBOARD LANGUAGE WIDGET
export const WIDGET_KEYBOARD_LANGUAGE_WIDTH = 302;
export const WIDGET_KEYBOARD_LANGUAGE_PADDING = 10;
export const WIDGET_KEYBOARD_LANGUAGE_ITEM_WIDTH = WIDGET_KEYBOARD_LANGUAGE_WIDTH;
export const WIDGET_KEYBOARD_LANGUAGE_ITEM_HEIGHT = 60;
export const WIDGET_KEYBOARD_LANGUAGE_ITEM_SELECTED_BACKGROUND_COLOR = SECONDARY_COLOR;
export const WIDGET_KEYBOARD_LANGUAGE_ITEM_SHORT_NAME_WIDTH = 60;
export const WIDGET_KEYBOARD_LANGUAGE_ITEM_SHORT_NAME_HEIGHT = WIDGET_KEYBOARD_LANGUAGE_ITEM_HEIGHT;
export const WIDGET_KEYBOARD_LANGUAGE_ITEM_SHORT_NAME_PADDING = new UIOffset(5, UIEdgeSet.top);
export const WIDGET_KEYBOARD_LANGUAGE_ITEM_DESCRIPTION_X = WIDGET_KEYBOARD_LANGUAGE_ITEM_SHORT_NAME_WIDTH + 10;
export const WIDGET_KEYBOARD_LANGUAGE_ITEM_DESCRIPTION_WIDTH = WIDGET_KEYBOARD_LANGUAGE_ITEM_WIDTH - WIDGET_KEYBOARD_LANGUAGE_ITEM_DESCRIPTION_X;
export const WIDGET_KEYBOARD_LANGUAGE_ITEM_DESCRIPTION_HEIGHT = WIDGET_KEYBOARD_LANGUAGE_ITEM_HEIGHT;
export const WIDGET_KEYBOARD_LANGUAGE_ITEM_DESCRIPTION_PADDING = new UIOffset(5, UIEdgeSet.top);