export const ZIP_VERSION = 20; // zip version 2.0
export const LOCAL_FILE_HEADER_SIGNATURE = 0x04034b50;
export const CENTRAL_DIRECTORY_FILE_HEADER_SIGNATURE = 0x02014b50;
export const END_OF_CENTRAL_DIRECTORY_SIGNATURE = 0x06054b50;

export const CONFIG = {
    ZIP_VERSION,
    LOCAL_FILE_HEADER_SIGNATURE,
    CENTRAL_DIRECTORY_FILE_HEADER_SIGNATURE,
    END_OF_CENTRAL_DIRECTORY_SIGNATURE,
}

export default CONFIG